language: csharp
sudo: required
dist: trusty

dotnet: 2.0.3
mono:
  - 5.10.0
  - latest # => "stable release"
  - alpha
  - beta
  - weekly # => "latest commits"
os:
  - linux
  - osx

addons:
  apt:
    packages:
    - dotnet-sharedframework-microsoft.netcore.app-1.1.2

script:
  - ./build.sh

matrix:
  fast_finish: true
  allow_failures:
    - mono: latest
    - mono: alpha
    - mono: beta
    - mono: weekly
