language: csharp
sudo: required
dist: trusty

dotnet: 2.1.4
mono:
  - 5.10.0
  - latest # => "stable release"
  - alpha
  - beta
  - weekly # => "latest commits"
os:
  - linux

addons:
  apt:
    packages:
    - dotnet-sharedframework-microsoft.netcore.app-1.1.2

before_script:
 - if [ "$TRAVIS_OS_NAME" == "linux" ];
   then export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:~/.nuget/packages/libuv/1.10.0/runtimes/linux-x64/native;
   else ln -s ~/.nuget/packages/libuv/1.10.0/runtimes/osx/native/libuv.dylib /usr/local/lib/libuv.dylib;
   fi

script:
  - ./build.sh

matrix:
  fast_finish: true
  allow_failures:
    - mono: latest
    - mono: alpha
    - mono: beta
    - mono: weekly
