// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Hopac.Websockets.Tests")>]
[<assembly: AssemblyProductAttribute("Hopac.Websockets")>]
[<assembly: AssemblyVersionAttribute("0.4.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2018-05-16T00:00:00.0000000")>]
[<assembly: AssemblyFileVersionAttribute("0.4.0")>]
[<assembly: AssemblyInformationalVersionAttribute("0.4.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","release")>]
[<assembly: AssemblyMetadataAttribute("GitHash","04e38375fd8e8ee3a17d7be41a7fdf900469d9ae")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Hopac.Websockets.Tests"
    let [<Literal>] AssemblyProduct = "Hopac.Websockets"
    let [<Literal>] AssemblyVersion = "0.4.0"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2018-05-16T00:00:00.0000000"
    let [<Literal>] AssemblyFileVersion = "0.4.0"
    let [<Literal>] AssemblyInformationalVersion = "0.4.0"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "release"
    let [<Literal>] AssemblyMetadata_GitHash = "04e38375fd8e8ee3a17d7be41a7fdf900469d9ae"
