// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Hopac.Websockets")>]
[<assembly: AssemblyProductAttribute("Hopac.Websockets")>]
[<assembly: AssemblyVersionAttribute("0.3.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2018-04-03T00:00:00.0000000")>]
[<assembly: AssemblyFileVersionAttribute("0.3.0")>]
[<assembly: AssemblyInformationalVersionAttribute("0.3.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","alpha")>]
[<assembly: AssemblyMetadataAttribute("GitHash","531e68b531ec8d5615186c2366c9b02f86f5a234")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Hopac.Websockets"
    let [<Literal>] AssemblyProduct = "Hopac.Websockets"
    let [<Literal>] AssemblyVersion = "0.3.0"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2018-04-03T00:00:00.0000000"
    let [<Literal>] AssemblyFileVersion = "0.3.0"
    let [<Literal>] AssemblyInformationalVersion = "0.3.0"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "alpha"
    let [<Literal>] AssemblyMetadata_GitHash = "531e68b531ec8d5615186c2366c9b02f86f5a234"
