// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Hopac.Websockets")>]
[<assembly: AssemblyProductAttribute("Hopac.Websockets")>]
[<assembly: AssemblyVersionAttribute("0.3.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2018-04-03T00:00:00.0000000")>]
[<assembly: AssemblyFileVersionAttribute("0.3.0")>]
[<assembly: AssemblyInformationalVersionAttribute("0.3.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","alpha")>]
[<assembly: AssemblyMetadataAttribute("GitHash","e47879c9f745640b1577f27a1787ab3b51ed73b7")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Hopac.Websockets"
    let [<Literal>] AssemblyProduct = "Hopac.Websockets"
    let [<Literal>] AssemblyVersion = "0.3.0"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2018-04-03T00:00:00.0000000"
    let [<Literal>] AssemblyFileVersion = "0.3.0"
    let [<Literal>] AssemblyInformationalVersion = "0.3.0"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "alpha"
    let [<Literal>] AssemblyMetadata_GitHash = "e47879c9f745640b1577f27a1787ab3b51ed73b7"
